timezone: "Asia/Seoul"

tick_duration:           # 증분 주기(범위 지정 시 랜덤)
  min: "15m"
  max: "90m"

increment:              # 한 번에 올릴 수 있는 조회수 범위(모든 단계 공통)
  min: 5
  max: 100

hourly_weights:         # 0~23시 가중치(합계 임의, 내부 정규화)
  "0": 0.01
  "1": 0.01
  "2": 0.01
  "3": 0.01
  "4": 0.01
  "5": 0.02
  "6": 0.03
  "7": 0.05
  "8": 0.07
  "9": 0.07
  "10": 0.06
  "11": 0.06
  "12": 0.08
  "13": 0.06
  "14": 0.05
  "15": 0.05
  "16": 0.05
  "17": 0.06
  "18": 0.07
  "19": 0.07
  "20": 0.07
  "21": 0.09
  "22": 0.04
  "23": 0.02

limits:
  max_hours: 336        # 최대 14일
  system_hour_cap: null # 선택: 시간당 상한(예: 500)
